### ISSUE TITLE
Create model and routes for shows

### ISSUE THREAD

**Issue by hellovolcano** [hellovolcano/streaming-service-tracker#3]
Create the model and routes for the specific shows that the user is interested in watching, with the following attributes

id
name
premiere date
service_id (foreign_key)

**Comment by Kate-github** [comment]
How are we gonna show information about the shows such as plot description, actors, episodes...are we gonna use a third party APIs?

**Comment by hellovolcano** [comment]
I was thinking at this stage we'd just have the user manually add the show name, premiere date, and streaming service/network to keep it simple. We could present linking our DB with external API info about the shows as a potential extension to the app.
