### ISSUE TITLE
Create a table/routes to store user preferences

### ISSUE THREAD

**Issue by hellovolcano** [hellovolcano/streaming-service-tracker#4]
As a user, I want to be able to see a rollup of my budget, any streaming service renewals that are upcoming, and reminders for the shows that I want to watch.

We'll need to store the following in a table for user preferences:

- id
- active streaming services
- notification preferences (text message? no notifications? how many days before the subscription renews, etc)

**Comment by Kate-github** [comment]
I can work on this. what preferences should we be saving?

**Comment by hellovolcano** [comment]
hey Kate-- i removed this from the project view but forgot to close it here. 

Look at this view for work items: https://github.com/users/hellovolcano/projects/2
