### ISSUE TITLE
Create a user dashboard

### ISSUE THREAD

**Issue by hellovolcano** [hellovolcano/streaming-service-tracker#5]
- View current subscriptions and a rollup of monthly cost
- Add a show to track
- Change status of streaming services (active vs inactive)
- View upcoming renewals

**Comment by Kate-github** [comment]
Do we need to implement notification in this project? This feature is not required so should we just remove it?

**Comment by hellovolcano** [comment]
That's a good question -- I think we talked bout using the text notification library as our "extra" technology/library/etc in order to fulfill that acceptance criteria.
